import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { useSession } from './useSession.js';
import { useRecommendations } from './useRecommendations.js';
import { useCalculations } from './useCalculations.js';
import { celsiusToFahrenheit } from '../utils/temperatureUtils.js';

/** ISO timestamp on a fixed day, so the assertions read as a timeline */
function at(hour, minute = 0) {
  const hh = String(hour).padStart(2, '0');
  const mm = String(minute).padStart(2, '0');
  return `2026-08-22T${hh}:${mm}:00.000Z`;
}

/**
 * The reported bug, end to end and in the units it was reported in: a Celsius
 * cook where the suggested temperature has to be settable on a real dial, and
 * where logging the change must not move the suggestion by the same amount
 * again.
 */
describe('a Celsius cook told to lower the oven', () => {
  let session;
  let rec;

  beforeEach(() => {
    localStorage.clear();
    vi.useFakeTimers();
    vi.setSystemTime(new Date(at(13)));

    session = useSession();
    session.startSession({
      units: 'C',
      pullTempF: celsiusToFahrenheit(65),
      initialOvenTemp: celsiusToFahrenheit(112),
      desiredServeTime: at(16)
    });

    // Four hours of steady climbing, well ahead of a 16:00 serve
    session.addReading(30, at(10));
    session.addReading(40, at(11));
    session.addReading(48, at(12));
    session.addReading(55, at(13));

    rec = useRecommendations();
  });

  afterEach(() => {
    session.endSession();
    vi.useRealTimers();
    localStorage.clear();
  });

  it('suggests a temperature the dial can actually be set to', () => {
    expect(rec.action.value).toBe('lower');
    // Not 98°C, which is what the raw Fahrenheit arithmetic works out to
    expect(rec.suggestedTemp.value % 5).toBe(0);
    expect(rec.suggestedTempFormatted.value).toBe('100°C');
    expect(rec.message.value).toContain('100°C');
  });

  it('accepts the change instead of asking for the same one again', () => {
    vi.setSystemTime(new Date(at(13, 6)));
    session.addOvenEvent(100, at(13, 5));

    expect(rec.awaitingEffect.value).toBe(true);
    expect(rec.action.value).toBe('settling');
    expect(rec.changeAmount.value).toBe(0);
    // The old behaviour: another full step down, to 90°C
    expect(rec.suggestedTempFormatted.value).toBe('100°C');
    expect(rec.message.value).toContain('100°C');
    expect(rec.message.value).not.toMatch(/[{}]/);
    expect(rec.waitMinutes.value).toBe(14);
    expect(rec.message.value).toContain('14 min');
  });

  it('accepts a setting the user rounded to their own dial', () => {
    vi.setSystemTime(new Date(at(13, 6)));
    session.addOvenEvent(100, at(13, 5));
    // Then nudged it again, to a mark they preferred
    vi.setSystemTime(new Date(at(13, 8)));
    session.addOvenEvent(98, at(13, 7));

    expect(rec.action.value).toBe('settling');
    expect(rec.suggestedTempFormatted.value).toBe('98°C');
    expect(rec.reasoning.value).toMatch(/nothing to change/);
  });

  it('reassesses from the new setting once readings show its effect', () => {
    vi.setSystemTime(new Date(at(13, 6)));
    session.addOvenEvent(100, at(13, 5));

    // Two readings past the thermal lag.
    session.addReading(56, at(13, 25));
    session.addReading(57, at(13, 45));
    vi.setSystemTime(new Date(at(13, 46)));

    // The plumbing property, which is what this test is for: the settling window
    // has closed, so the advice is derived from the setting the readings actually
    // describe rather than anchored to the previous one.
    expect(rec.awaitingEffect.value).toBe(false);
    expect(rec.suggestedTemp.value % 5).toBe(0);
  });

  it('does not claim confidence in readings no single curve fits', () => {
    /**
     * The fixture above - 55 °C at 13:00 then 56 and 57 over the next 45 minutes -
     * is an abrupt flattening no roast produces: a 12 °C reduction in oven
     * temperature slows a core, it does not stop one dead. The old linear model
     * read the last two readings, called it 5 °F/hr, and confidently advised a
     * raise. The curve cannot reproduce the shape at all, and says so - residuals
     * running -11, -9, -3, +3, +7 °F, a systematic S rather than scatter.
     *
     * Reporting low confidence on unphysical data is the improvement. It is also
     * the reason the assertion above does not name a direction: the honest answer
     * to this fixture is "these readings do not describe a roast".
     */
    vi.setSystemTime(new Date(at(13, 6)));
    session.addOvenEvent(100, at(13, 5));
    session.addReading(56, at(13, 25));
    session.addReading(57, at(13, 45));
    vi.setSystemTime(new Date(at(13, 46)));

    const { confidence } = useCalculations();
    expect(confidence.value.level).toBe('low');
    expect(confidence.value.code).toBe('loose-fit');
  });
});

describe('a cook that is genuinely running late', () => {
  /**
   * Readings generated by walking the thermal model at a k slow enough to miss
   * the serve time, so the "raise the oven" verdict is one a real roast would
   * earn. The previous version of this test forced the verdict with an abrupt
   * flattening instead, which is why it had to change.
   */
  let session;
  let rec;

  beforeEach(() => {
    localStorage.clear();
    vi.useFakeTimers();
    // The clock is wound back for startSession, which stamps its opening oven
    // event with `new Date()`. Started at 13:46 that event would be the NEWEST
    // one - after the 13:05 change - and the settling window would never close.
    vi.setSystemTime(new Date(at(9, 30)));

    session = useSession();
    session.startSession({
      units: 'C',
      pullTempF: celsiusToFahrenheit(65),
      initialOvenTemp: celsiusToFahrenheit(112),
      desiredServeTime: at(16),
      restMinutes: 0
    });
    vi.setSystemTime(new Date(at(13, 46)));

    // A large, slow roast: k = 0.0038 /min, which is a 9 lb shoulder's sort of
    // number. Reaches 47.2 °C by 13:45 against a 65 °C target, which the model
    // projects 180 minutes out - 45 minutes past the serve time.
    [[30, at(10)], [31.8, at(11)], [36.3, at(12)], [42.3, at(13)],
      [45, at(13, 25)], [47.2, at(13, 45)]]
      .forEach(([temp, timestamp]) => session.addReading(temp, timestamp));
    session.addOvenEvent(100, at(13, 5));

    rec = useRecommendations();
  });

  afterEach(() => {
    session.endSession();
    vi.useRealTimers();
    localStorage.clear();
  });

  it('asks for more heat, from the setting the readings describe', () => {
    const { scheduleStatus, confidence } = useCalculations();
    expect(confidence.value.code).toBe('good-fit');
    expect(scheduleStatus.value).toBe('late');
    expect(rec.awaitingEffect.value).toBe(false);
    expect(rec.action.value).toBe('raise');
    expect(rec.suggestedTemp.value).toBeGreaterThan(100);
    expect(rec.suggestedTemp.value % 5).toBe(0);
  });
});

/**
 * The stall band, rendered in the cook's own unit.
 *
 * STALL_REFUSAL_REASON carries a `{stallBand}` placeholder rather than a
 * "150–165 °F" literal, and blockerReason is routed through useRecommendations'
 * substitute() so it resolves. The `rendered-text` invariant in
 * tools/sim/invariants.js checks that field for exactly two failures - an
 * unsubstituted placeholder, and a Fahrenheit temperature shown to a Celsius cook -
 * but no cook on the simulated deck ever reaches a rate disagreement, so neither
 * half of that check has ever seen this sentence. It is asserted here instead.
 */
describe('a stalling shoulder, in each unit', () => {
  let session;
  let rec;

  /**
   * A shoulder whose readings flatten inside the stall band. The plateau has to be
   * real - assessRateAgreement compares the observed slope against the model's, and
   * the whole sentence is unreachable until it disagrees.
   */
  function stalling(units) {
    localStorage.clear();
    vi.useFakeTimers();
    vi.setSystemTime(new Date(at(20)));

    session = useSession();
    session.startSession({
      units,
      meatType: 'Pork Shoulder',
      weight: 9,
      pullTempF: 203,
      servingTempF: 203,
      carryoverF: 0,
      restMinutes: 30,
      initialOvenTemp: 250,
      desiredServeTime: at(23)
    });

    const F = [45, 90, 130, 151, 154, 155, 155.2, 155.4];
    F.forEach((tempF, i) => {
      const shown = units === 'C' ? Math.round(((tempF - 32) * 5 / 9) * 10) / 10 : tempF;
      session.addReading(shown, at(13 + i));
    });

    rec = useRecommendations();
    return rec;
  }

  afterEach(() => {
    session?.endSession();
    vi.useRealTimers();
    localStorage.clear();
  });

  it('names the stall and its band in Fahrenheit', () => {
    const r = stalling('F');
    // The guard: without the refusal there is no sentence to check.
    expect(r.blockerType.value).toBe('no_projection');
    expect(r.blockerReason.value).toMatch(/this is the stall/i);
    expect(r.blockerReason.value).toContain('150–165°F');
    expect(r.blockerReason.value).not.toContain('{stallBand}');
  });

  it('converts the band for a Celsius cook, rather than showing Fahrenheit', () => {
    const r = stalling('C');
    expect(r.blockerType.value).toBe('no_projection');
    expect(r.blockerReason.value).toMatch(/this is the stall/i);
    // 150-165 °F is 66-74 °C. A band left in °F here is the exact failure the
    // rendered-text invariant's second half was written for.
    expect(r.blockerReason.value).toContain('66–74°C');
    expect(r.blockerReason.value).not.toMatch(/°\s?F/);
    expect(r.blockerReason.value).not.toContain('{stallBand}');
  });
});
